os: Visual Studio 2022

version: 2.2.1-alpha-{build}

init:
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")

      {
          Update-AppveyorBuild -Version $($env:APPVEYOR_REPO_TAG_NAME.TrimStart('v'))
      }

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: "{version}"
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"
  informational_version: "{version}"

nuget:
  account_feed: true
  project_feed: true

before_build:
 - ps: dotnet restore

artifacts:
 - path: '**\*.nupkg'

notifications:
 - provider: Slack
   auth_token:
     secure: fOssPHTsqm6seWcnywN2TJE9gLtRdd1iXLRWWWWAhx4atR0u0ECGb/9Ij/gI/zafJI+FQvevEemi9epjeRhV/g==
   channel: rest-api
   template: "<{{buildUrl}}|Build {{projectName}} {{buildVersion}} {{status}}> Commit <{{commitUrl}}|{{commitId}}> by {{commitAuthor}} on {{commitDate}}: _{{commitMessage}}_"
